package com.manewreck.sdapp.mobile.ui

import com.manewreck.sdapp.mobile.core.sync.CloudProviderType
import com.manewreck.sdapp.mobile.data.AccountSortMode
import com.manewreck.sdapp.mobile.data.AppLanguage

data class AppStrings(
    val accounts: String,
    val settings: String,
    val sync: String,
    val qr: String,
    val account: String,
    val ok: String,
    val cancel: String,
    val vaultStatus: String,
    val importMaFile: String,
    val importIntro: String,
    val noAccountsYet: String,
    val noAccountsBody: String,
    val currentlySelected: String,
    val cloudBackupReady: String,
    val localVaultOnly: String,
    val favoriteCloudReady: String,
    val steamGuardCode: String,
    val noAccountSelected: String,
    val importAccountToGenerate: String,
    val secondsRemaining: String,
    val scanQr: String,
    val copyCode: String,
    val codeCopied: String,
    val qrLogin: String,
    val selectedAccount: String,
    val scanSteamQrAs: String,
    val none: String,
    val qrComingSoon: String,
    val cameraPermissionRequired: String,
    val grantCameraAccess: String,
    val previousAccount: String,
    val nextAccount: String,
    val chooseAccount: String,
    val qrDetected: String,
    val qrApprovalNotImplemented: String,
    val qrApproving: String,
    val qrApproved: String,
    val scanAgain: String,
    val cloudSync: String,
    val provider: String,
    val vaultAccounts: String,
    val lastSyncNotYet: String,
    val pull: String,
    val push: String,
    val testConnection: String,
    val cloudSettingsHint: String,
    val cloudUrl: String,
    val cloudLogin: String,
    val cloudPassword: String,
    val cloudFolder: String,
    val save: String,
    val settingsIntro: String,
    val importedAccounts: String,
    val language: String,
    val english: String,
    val russian: String,
    val cloudSettingsSaved: String,
    val languageSaved: String,
    val failedToOpenFile: String,
    val importedPrefix: String,
    val security: String,
    val appPin: String,
    val enterPin: String,
    val unlock: String,
    val unlockWithBiometrics: String,
    val biometrics: String,
    val setPin: String,
    val pinSaved: String,
    val pinTooShort: String,
    val wrongPin: String,
    val appLocked: String,
    val appLockedBody: String,
    val biometricEnabled: String,
    val biometricUnavailable: String,
    val syncSuccess: String,
    val syncFailed: String,
    val connectionSuccess: String,
    val encryptionEnabled: String,
    val encryptedVaultReady: String,
    val accountSearch: String,
    val enableAccountSearch: String,
    val accountSort: String,
    val sortAlphabetical: String,
    val sortLevel: String,
    val searchAccountsPlaceholder: String,
    val noSearchResults: String,
    val accountsDisplay: String,
    val favoritesFirst: String,
    val desktopPairingTitle: String,
    val desktopPairingPrompt: String,
    val shareCloudSettings: String,
    val desktopPairingSent: String,
    val desktopPairingFailed: String,
)

fun appStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.Russian -> AppStrings(
            accounts = "Аккаунты",
            settings = "Настройки",
            sync = "Синхр.",
            qr = "QR",
            account = "Аккаунт",
            ok = "OK",
            cancel = "Отмена",
            vaultStatus = "Статус хранилища",
            importMaFile = "Импорт .maFile",
            importIntro = "Импортируй maFiles и используй Steam Guard коды прямо на этом устройстве.",
            noAccountsYet = "Аккаунтов пока нет",
            noAccountsBody = "Выбери файл Steam Desktop Authenticator `.maFile` из памяти телефона, чтобы заполнить хранилище.",
            currentlySelected = "Выбран сейчас",
            cloudBackupReady = "Облачная копия готова",
            localVaultOnly = "Только локальное хранилище",
            favoriteCloudReady = "Избранный • облачная копия готова",
            steamGuardCode = "Код Steam Guard",
            noAccountSelected = "Аккаунт не выбран",
            importAccountToGenerate = "Импортируй аккаунт, чтобы получать живые коды Steam Guard.",
            secondsRemaining = "сек. осталось",
            scanQr = "Скан QR",
            copyCode = "Копировать код",
            codeCopied = "Код скопирован",
            qrLogin = "QR вход",
            selectedAccount = "Выбранный аккаунт",
            scanSteamQrAs = "Сканируй Steam QR-код для входа как:",
            none = "Нет",
            qrComingSoon = "Отсканируй Steam QR-код и подтверди вход выбранным аккаунтом.",
            cameraPermissionRequired = "Для сканирования QR нужен доступ к камере.",
            grantCameraAccess = "Разрешить доступ к камере",
            previousAccount = "Предыдущий",
            nextAccount = "Следующий",
            chooseAccount = "Выбрать аккаунт",
            qrDetected = "Steam QR обнаружен",
            qrApprovalNotImplemented = "Не удалось подтвердить QR-вход Steam.",
            qrApproving = "Подтверждаем QR-вход через Steam…",
            qrApproved = "QR-вход подтверждён для выбранного аккаунта.",
            scanAgain = "Сканировать снова",
            cloudSync = "Облачная синхронизация",
            provider = "Провайдер",
            vaultAccounts = "Аккаунтов в хранилище",
            lastSyncNotYet = "Синхронизации ещё не было",
            pull = "Загрузить",
            push = "Отправить",
            testConnection = "Проверить",
            cloudSettingsHint = "Локальный vault уже шифруется. Эти данные используются для WebDAV pull/push зашифрованных `.maFile` и `manifest`.",
            cloudUrl = "URL WebDAV / endpoint",
            cloudLogin = "Логин",
            cloudPassword = "Пароль",
            cloudFolder = "Папка в облаке",
            save = "Сохранить",
            settingsIntro = "Локализация, безопасность, синхронизация и параметры аккаунтов.",
            importedAccounts = "Импортировано аккаунтов",
            language = "Язык",
            english = "English",
            russian = "Русский",
            cloudSettingsSaved = "Настройки облака сохранены",
            languageSaved = "Язык сохранён",
            failedToOpenFile = "Не удалось открыть .maFile",
            importedPrefix = "Импортирован",
            security = "Безопасность",
            appPin = "PIN приложения",
            enterPin = "Введите PIN",
            unlock = "Разблокировать",
            unlockWithBiometrics = "Войти по биометрии",
            biometrics = "Биометрия",
            setPin = "Сохранить PIN",
            pinSaved = "PIN сохранён",
            pinTooShort = "PIN должен содержать минимум 4 цифры",
            wrongPin = "Неверный PIN",
            appLocked = "Приложение заблокировано",
            appLockedBody = "Разблокируй SDA++ Mobile PIN-кодом или биометрией.",
            biometricEnabled = "Биометрия включена",
            biometricUnavailable = "Биометрия недоступна на этом устройстве",
            syncSuccess = "Синхронизация завершена",
            syncFailed = "Ошибка синхронизации",
            connectionSuccess = "Подключение к WebDAV успешно",
            encryptionEnabled = "Шифрование включено",
            encryptedVaultReady = "Локальный vault хранит `manifest` и `.maFile` в зашифрованном виде.",
            accountSearch = "Поиск по аккаунтам",
            enableAccountSearch = "Включить поиск по аккаунтам",
            accountSort = "Сортировка аккаунтов",
            sortAlphabetical = "A-Z",
            sortLevel = "По уровню",
            searchAccountsPlaceholder = "Поиск аккаунтов",
            noSearchResults = "Ничего не найдено",
            accountsDisplay = "Отображение аккаунтов",
            favoritesFirst = "Избранные всегда сверху",
            desktopPairingTitle = "Подключение к SDA++ Desktop",
            desktopPairingPrompt = "Передать этому компьютеру URL, логин, пароль приложения и папку WebDAV? Steam-секреты и файлы аккаунтов не передаются. Оба устройства должны быть в одной частной сети.",
            shareCloudSettings = "Передать",
            desktopPairingSent = "Настройки WebDAV безопасно переданы в SDA++ Desktop.",
            desktopPairingFailed = "Не удалось подключиться к SDA++ Desktop.",
        )
        AppLanguage.English -> AppStrings(
            accounts = "Accounts",
            settings = "Settings",
            sync = "Sync",
            qr = "QR",
            account = "Account",
            ok = "OK",
            cancel = "Cancel",
            vaultStatus = "Vault status",
            importMaFile = "Import .maFile",
            importIntro = "Import your maFiles and use Steam Guard codes directly on this device.",
            noAccountsYet = "No accounts yet",
            noAccountsBody = "Choose a Steam Desktop Authenticator .maFile from your phone storage to populate the vault.",
            currentlySelected = "Currently selected",
            cloudBackupReady = "Cloud backup ready",
            localVaultOnly = "Local vault only",
            favoriteCloudReady = "Favorite • Cloud backup ready",
            steamGuardCode = "Steam Guard code",
            noAccountSelected = "No account selected",
            importAccountToGenerate = "Import an account to generate live Steam Guard codes.",
            secondsRemaining = "seconds remaining",
            scanQr = "Scan QR",
            copyCode = "Copy code",
            codeCopied = "Code copied",
            qrLogin = "QR Login",
            selectedAccount = "Selected account",
            scanSteamQrAs = "Scan a Steam QR code to sign in as:",
            none = "None",
            qrComingSoon = "Scan a Steam QR code and approve sign-in with the selected account.",
            cameraPermissionRequired = "Camera access is required to scan Steam QR codes.",
            grantCameraAccess = "Grant camera access",
            previousAccount = "Previous",
            nextAccount = "Next",
            chooseAccount = "Choose account",
            qrDetected = "Steam QR detected",
            qrApprovalNotImplemented = "Steam QR approval failed.",
            qrApproving = "Approving the Steam QR login…",
            qrApproved = "QR login approved for the selected account.",
            scanAgain = "Scan again",
            cloudSync = "Cloud Sync",
            provider = "Provider",
            vaultAccounts = "Vault accounts",
            lastSyncNotYet = "Not synced yet",
            pull = "Pull",
            push = "Push",
            testConnection = "Test",
            cloudSettingsHint = "The local vault is already encrypted. These credentials drive WebDAV pull/push of encrypted `.maFile` and `manifest` files.",
            cloudUrl = "WebDAV URL / endpoint",
            cloudLogin = "Login",
            cloudPassword = "Password",
            cloudFolder = "Cloud folder",
            save = "Save",
            settingsIntro = "Localization, security, sync, and account preferences.",
            importedAccounts = "Imported accounts",
            language = "Language",
            english = "English",
            russian = "Russian",
            cloudSettingsSaved = "Cloud settings saved",
            languageSaved = "Language saved",
            failedToOpenFile = "Failed to open .maFile",
            importedPrefix = "Imported",
            security = "Security",
            appPin = "App PIN",
            enterPin = "Enter PIN",
            unlock = "Unlock",
            unlockWithBiometrics = "Unlock with biometrics",
            biometrics = "Biometrics",
            setPin = "Save PIN",
            pinSaved = "PIN saved",
            pinTooShort = "PIN must be at least 4 digits",
            wrongPin = "Wrong PIN",
            appLocked = "App locked",
            appLockedBody = "Unlock SDA++ Mobile with your PIN or biometrics.",
            biometricEnabled = "Biometrics enabled",
            biometricUnavailable = "Biometrics are unavailable on this device",
            syncSuccess = "Sync completed",
            syncFailed = "Sync failed",
            connectionSuccess = "WebDAV connection successful",
            encryptionEnabled = "Encryption enabled",
            encryptedVaultReady = "The local vault stores `manifest` and `.maFile` payloads in encrypted form.",
            accountSearch = "Account search",
            enableAccountSearch = "Enable account search",
            accountSort = "Account sorting",
            sortAlphabetical = "A-Z",
            sortLevel = "By level",
            searchAccountsPlaceholder = "Search accounts",
            noSearchResults = "No results found",
            accountsDisplay = "Accounts display",
            favoritesFirst = "Favorites always on top",
            desktopPairingTitle = "Connect SDA++ Desktop",
            desktopPairingPrompt = "Share the WebDAV URL, login, app password, and folder with this computer? Steam secrets and account files are not sent. Both devices must be on the same private network.",
            shareCloudSettings = "Share",
            desktopPairingSent = "WebDAV settings were securely sent to SDA++ Desktop.",
            desktopPairingFailed = "Could not connect to SDA++ Desktop.",
        )
    }
}

fun cloudProviderLabel(provider: CloudProviderType): String {
    return when (provider) {
        CloudProviderType.WebDav -> "WebDAV"
        CloudProviderType.GoogleDrive -> "Google Drive"
        CloudProviderType.Dropbox -> "Dropbox"
        CloudProviderType.OneDrive -> "OneDrive Personal"
        CloudProviderType.S3Compatible -> "S3-compatible"
    }
}

fun accountSortModeLabel(mode: AccountSortMode, strings: AppStrings): String {
    return when (mode) {
        AccountSortMode.Alphabetical -> strings.sortAlphabetical
        AccountSortMode.Level -> strings.sortLevel
    }
}
